controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_admin_reservation_index_select:
    path: /admin/reservation/select
    controller: App\Controller\AdminReservationController::select
    methods: [GET]

    