<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1PtDNWN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1PtDNWN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1PtDNWN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1PtDNWN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1PtDNWN\App_KernelDevDebugContainer([
    'container.build_hash' => '1PtDNWN',
    'container.build_id' => '11383765',
    'container.build_time' => 1685021835,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1PtDNWN');
